services:
  - type: web
    name: workforce-manager-server
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: workforce-db
          property: connectionString
      - key: CLIENT_URL
        value: https://davittorino.vercel.app
      - key: SESSION_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
    autoDeploy: true

databases:
  - name: workforce-db
    plan: free
    ipAllowList: [] 